#!/bin/bash
d="$1"
for i in www; do
  if (getent hosts $i.$1 > /dev/null); then
    d="$d,$i.$1";
  fi
done
# We are using the "standalone" letsencrypt plugin, which runs its own
# webserver, so we need to temporarily free up the HTTP(S) ports by stopping
# our own Apache.
systemctl stop apache2
/root/letsencrypt/letsencrypt-auto --installer apache -c /etc/letsencrypt/cli.conf -d $d
systemctl start apache2
